checkov:
  quiet: true
  soft_fail: false

  framework:
    - terraform

  output: cli

  skip_path:
    - .terraform
    - modules/vendor

  skip_checks:
    - CKV_AWS_18
    - CKV_AWS_52
    - CKV_AWS_144 

  suppress_inline_comments: true

